name: Demo

on:
  push:
    branches: 
      - main
      - dev
    
  pull_request:
    branches:
      - main
      - dev

  # Allows us to run the workflow whenever we want from GitHub Actions
  workflow_dispatch:
        

concurrency:
  group: dill-ci-${{ github.ref }}
  cancel-in-progress: true


jobs:
  pipeline:

    strategy:
      matrix:
        include:
          - platform: 'ubuntu-latest'
          - platform: 'macos-latest'
          - platform: 'windows-latest'

    runs-on: ${{ matrix.platform }}


    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          
      - name: Install Node dependencies
        run: npm install

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          
      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Update sbt
        shell: bash
        run: sbt update

      - name: Run sbt test
        shell: bash
        run: sbt test
